---
abstract: 'Load and merge configuration from different file formats, transparently'
author:
  - 'jason hord <pravus@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::Deep: 0.00
  Test::More: 0.00
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Config-Merged
no_index:
  directory:
    - inc
    - t
requires:
  Config::Any: 0.00
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.05
